---
apiVersion: v1
kind: Pod 
metadata:
  name: my-sql
  labels:
    env: dev
    app: my-sql
spec:
  containers:
    - image: mysql:9
      name: my-sql
      resources:
        requests:
          memory: 256Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 1000m
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword 
        - name: MYSQL_DATABASE
          value: library
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: password 
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: volume 
          readOnly: false
  volumes:
    - name: volume 
      persistentVolumeClaim:
        claimName: pvc-azuredisk