---
apiVersion: v1
kind: Pod 
metadata:
  name: my-sql
  labels:
    env: dev
    app: my-sql
spec:
  containers:
    - image: mysql:9
      name: my-sql
      resources:
        requests:
          memory: 256Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 1000m
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: volume 
          readOnly: false
  volumes:
    - name: volume 
      persistentVolumeClaim:
        claimName: pvc-azuredisk