---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpet
  labels:
    app: spc
spec:
  repicas: 2
  selector:
    matchlabels:
      app: spc
      env: dev
  template:
      metadata:
        labels:
          app: spc
          env: dev
      spec:
        containers:
          - name: pod
            image: shaikkhajaibrahim/spcjan2024:1.0
            ports:
              - containerPort: 8080
            resources: 
              requests: 
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "500m"
  
