---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-ns
  labels:
    env: dev
    app: nginx-ns
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nginx-ns
  template:
    metadata:
      labels:
        app: nginx-ns
    spec:
      containers:
      - image: nginx
        name: nginx-ns
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: 24Mi
            cpu: 128m
          limits:
            memory: 256Mi
            cpu: 500m

---
apiVersion: v1
kind: Service 
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-svc
  ports:
    - port: 80
      targetPort: 80 
      

    
      