---
apiVersion: v1
kind: Pod 
metadata:
  name: alpine-pod
  namespace: default
spec:
  containers:
    - name: alpine-pod
      image: alpine 
      ports:
        - containerPort: 8000
      args:
        - sleep
        - 30s