apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
  labels:
    env: Dev
    app: spc
spec:
  replicas: 3
  selector:
    matchLabels:
      env: Dev
      app: spc
  template:
    metadata:
      labels:
        env: Dev
        app: spc  # Ensure this matches the selector
    spec:
      containers:
        - name: web
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "300m"
          
---
apiVersion: v1 
kind: Service 
metadata:
  name: spc-svc
spec:
  type: NodePort
  selector:
    env: Dev
    app: spc
  ports:
    - port: 8080
      targetPort: 8080