---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: my-dynamic-storage-class
  resources:
    requests:
      storage: 1Gi