apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage-class
provisioner: disk.csi.azure.com
parameters:
  kind: Managed
  cachingmode: ReadWriteOnce
  skuName: Standard_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true