---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stsflset
  labels:
    env: dev
    app: sts 
spec:
  serviceName: sts-svc 
  minReadySeconds: 5 
  replicas: 2         
  selector:
    matchLabels:
      app: sts
  template:
    metadata:
      labels:
        app: sts      
    spec:
      containers:
        - name: web
          image: nginx:1.27  
          ports:
            - containerPort: 80  
          resources:
            requests:
              memory: "64Mi"   
              cpu: "128m"      
            limits:
              memory: "256Mi"  
              cpu: "500m"      
          volumeMounts:
            - name: sts          
              mountPath: /usr/share/nginx/html  

  volumeClaimTemplates:
    - metadata: 
        name: sts            
      spec:
        accessModes: [ "ReadWriteOnce" ]  
        storageClassName: "my-storage-class"  
        resources:
          requests:
            storage: "1Gi"     

---
apiVersion: v1
kind: Service 
metadata:
  name: sts-svc                  
  labels:
    env: dev                     
    app: sts 
spec:
  ports: 
    - port: 80                   
      targetPort: 80            
  clusterIP: None                
  selector:
    app: sts                     