---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: books-svc
  labels:
    env: dev
    app: books-svc
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-svc
  template:
    metadata:
      labels:
        app: books-svc
    spec:
      containers:
        - image: nginx 
          name: books-svc
          ports:
          - containerPort: 8000
          resources:
            requests:
              memory: 24Mi
              cpu: 128m
            limits:
              memory: 128Mi
              cpu: 500m 
          livenessProbe:  
            initialDelaySeconds: 10
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 8000
          readinessProbe:  
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
          startupProbe:   
            exec:
              command:
                - /bin/sh
                - -c 
                - ps aux | grep uvicorn
            initialDelaySeconds: 10
            successThreshold: 1
            failureThreshold: 3
            
                
---
apiVersion: v1 
kind: Service 
metadata:
  name: books-svc
spec:
  type: NodePort
  selector:
    app: books-svc
  ports:
    - port: 8000
      targetPort: 8000
        
        