---
apiVersion: v1
kind: Pod 
metadata:
  name: springpet
  labels:
   env: dev
   app: spc
spec:
  containers:
    - name: spc 
      image: shaikkhajaibrahim/spcjan2024:1.0
      resources: 
        requests:
         memory: "64Mi"
         cpu: "250m"
        limits:
         memory: "256Mi"
         cpu: "500m"
      ports:
        - containerPort: 8080
         