---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-daemon
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: hello-daemon
  template:
    metadata:
      labels:
        app: hello-daemon
    spec:
      containers:
        - name: myweb
          image:  fluent/fluentd:edge-debian
          resources:
            requests:
              memory: 24Mi
              cpu: 128m 
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 8000
                
    