---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-dy 
  labels:
    env: dev
    app: spc
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        env: dev
        app: spc
    spec:
      containers:
        - name: spc
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "24Mi"
              cpu: "100m"
            limits:
              memory: "124Mi"
              cpu: "500m"