apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: preschool-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: preschool
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resources:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

    