resources:
  requests:
    storage: 1G
accessmodes: 
 - ReadWriteOnce
storageclass: managed
resources:
  requests:
    storage: 1Gi
volume:
  name: web
containerport: 80
portname: web
containers:
  name: web
  image: nginx
  tag: 1.27
template:
  app: web
matchlabels:
  app: web
minReadySeconds: 5
replicas: 3