---
apiVersion: v1 
kind: Service 
metadata: 
  name: booksdb-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: booksdb
  ports:
    - port: 3306
      targetPort: 3306


---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: bksdb-sts
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: bksdb
  serviceName: booksdb-svc
  template:
    metadata:
      labels:
        app: bksdb
    spec:
      containers:
        - name: mysql
          image: mysql:9
          ports:
          - containerPort: 3306
          envFrom:
            - secretRef:
                name: bksdb-sec
          env:
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DB
              value: bksdb
          resources:
            requests:
              memory: 64M
              cpu: 128m 
            limits:
              memory: 256M
              cpu: 500m
          volumeMounts:
            - name: volume 
              mountPath: /var/lib/mysql
              subPath: mysql
  volumeClaimTemplates:
  - metadata:
      name: volume 
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: managed
      resources:
        requests: 
          storage: 1Gi
