---
apiVersion: v1
kind: Secret 
metadata:
  name: bksdb-sec 
data: 
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQK
  MYSQL_DB: YmtzZGI=

---
apiVersion: v1
kind: Secret 
metadata:
  name: usrdb-sec 
data: 
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQK
  MYSQL_DB: dXNyZGI=

---
apiVersion: v1
kind: Secret
metadata:
  name: bksdb-svc-sec
data:
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
  DATABASE_URL: bXlzcWw6Ly91c2VyOnBhc3N3b3JkQGJrc2RiLTAuYmtzZGItc3ZjOjMzMDYvYmtzZGI=

---
apiVersion: v1
kind: Secret
metadata:
  name: usrdb-svc-sec
data:
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
  DATABASE_URL: bXlzcWw6Ly91c2VyOnBhc3N3b3JkQHVzcmRiLTAudXNyZGItc3ZjOjMzMDYvdXNyZGI=

  
