---
apiVersion: v1 
kind: Service 
metadata: 
  name: usrdb-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: booksdb
  ports:
    - port: 5000
      targetPort: 5000


---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: usrdb-sts
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: usrdb
  serviceName: usrdb-svc
  template:
    metadata:
      labels:
        app: usrdb
    spec:
      containers:
        - name: mysql
          image: mysql:9
          ports:
          - containerPort: 5000
          envFrom:
            - secretRef:
                name: usrdb-sec
          env:
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DB
              value: usrdb
          volumeMounts:
            - name: volume 
              mountPath: /mnt/data
              subPath: data
    volumeClaimTemplates:
    - metadata:
        name: volume 
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: managed
        resources:
          requests: 
            storage: 1Gi
