---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels }}
spec:
  ports: 
  - port: {{ .Values.containerport }}
    name: {{ .Values.portname }}
  clusterIP: {{ .Values.clusterIP }}
  selector: 
    app: {{ .Values.selector }}