---
apiVersion: v1
kind: Secret 
metadata:
  name: usr-db-sec-key
data: 
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: dXNlcmRi

---
apiVersion: v1
kind: Secret
metadata:
  name: books-db-sec-key
data:
  POSTGRES_USER: IHVzZXI=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: Ym9va3NkYg==

---
apiVersion: v1 
kind: Secret
metadata:
  name: booksdb-sec-key
data:
  SECRET_KEY:  WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAYm9va3NkYi0wLmJvb2tzZGItc3ZjOjU0MzIvYm9va3NkYg== 

---
apiVersion: v1 
kind: Secret
metadata:
  name: usrdb-sec-key
data:
  SECRET_KEY:  WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
  DATABASE_URL:  cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAdXNlcnNkYi0wLnVzZXJzZGItc3ZjOjU0MzIvdXNlcnNkYg== 

  
   
  
