---
apiVersion: v1 
kind: Service 
metadata:
  name: usr-db-sec-key
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: usrdb 

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: usrdb
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: usrdb
  serviceName: usrdb-svc
  template:
    metadata:
      labels:
        app: usrdb
    spec:
      containers:
      - name: usrdb
        image: postgres:15-alpine
        envFrom:
          - secretRef:
              name: usrdb-sec-key
        env:
          - name:  POSTGRES_USER
            value: user
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: usrdb
        resources:                    
          requests:
            memory: 24Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
          - containerPort: 5432
        volumeMounts:
        - name: db 
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: managed
      resources:
        requests:
          storage: 1Gi


     
    
