---
namespace: web
replicas: 3
labels: cap
template: cap
image: nginx
tag: 1.27
name: web
ports: 8080
resources:
  limits:
    memory: 128Mi
    cpu: 500m

---
type: ClusterIP
ports: 
    port: 8080
    targetPort: 8080

---
namespace: web